<!doctype html>
<html ng-app="GED-2AS">

<head>
  <?php include INCLUSIONS_HTML_PATH  . DIRECTORY_SEPARATOR
  					. $this->page['template'] . DIRECTORY_SEPARATOR
  					. "head.phtml" ?>
</head>

<body>

  <header>
		<?php include INCLUSIONS_HTML_PATH  . DIRECTORY_SEPARATOR
					 . $this->page['template'] . DIRECTORY_SEPARATOR
					 . "header_html5.phtml" ?>
  </header>
  
  
  <?php include INCLUSIONS_HTML_PATH  . DIRECTORY_SEPARATOR
			   . $this->page['template'] . DIRECTORY_SEPARATOR
			   . "body.phtml" ?>
  
  
  <footer>
		<?php include INCLUSIONS_HTML_PATH  . DIRECTORY_SEPARATOR
					 . $this->page['template'] . DIRECTORY_SEPARATOR
					 . "footer_html5.phtml" ?>
  </footer>

<?php include INCLUSIONS_HTML_PATH  . DIRECTORY_SEPARATOR
			 . $this->page['template'] . DIRECTORY_SEPARATOR
			 . "bottom-javascript.phtml" ?>

</body>

</html>