<article>
 <h1>intégration du moteur d'écriture à la façon YAML</h1>
 <span class='date'><span class='jour'>8</span><br/><span class='mois'>AOUT</span><br/><span class='annee'>2016</span></span>
<h2>Ce qui suit est le fichier formatté dans DATA et généré à la volé par le formatteur YAML:</h2>
<pre>
 <?php print_r( $this->page['YAMLtext']->formated_text ); ?>
</pre>
 <h3>Voici ce qu'il reste a faire
 <p>Intégrer le YAML pour la configuration de l'application</p>
 </h3>
 <h4>Dernier Git le 3 aout 2016</h4>
 <h5>Acksop</h5>
 <h6>POO.formation.dev</h6>
 </article>