<article>
<h1>Intégration d'un orm simple à peu près fonctionnel</h1>
<span class='date'><span class='jour'>21</span><br/><span class='mois'>JUILLET</span><br/><span class='annee'>2019</span></span>
<h2>source : <a href='https://www.supinfo.com/articles/single/1750-architecture-mvc-php-1-modeles-orm'>https://www.supinfo.com/articles/single/1750-architecture-mvc-php-1-modeles-orm</a></h2>
 <h3>Voici ce qu'il reste à faire:
 <p>Tester avec une base de données les différents accès</p>
 </h3>
 </article>