<article>
<h1>Article numéro 1</h1>
<span class='date'><span class='jour'>27</span><br/><span class='mois'>JANVIER</span><br/><span class='annee'>2016</span></span>
<h2>Ceci est la page d'acceuil du site que vous êtes en train de créer </h2>
 <h3>Voici ce qu'il reste a faire:
 <p>Intégrer un chargement de fonction automatique à partir d'une action passer en url a la façon Wordpress</p>
 <p class='del' >Intégrer le wikini Core dans une page avec toutes les fonctionnalités d'écriture ( le 0.4.3 serait le top!)</p>
 <p>Intégrer une page de gestion des cookies existants dans l'application: un .txt par cookies et on rassemble tout pour les gérer</p>
 <p style='text-decoration: line-through;'>Intégrer des actions dans l'écriture d'articles ou de pages personnelles, exemple a faire avec les anciennes pages d'articles du B25<br /> en utilisant une seule page et plusieures actions</p>
 <p>Intégrer une dale bdd avec un modele d'envoi MVC-VM ou MVVM en JSON, pour tester avec un affichage ExtJS</p>
 <p>Intégrer une exploitation de la GED plus poussée avec les fichiers qui se download apr exemple</p>
 <p>Intégrer une exploitation de l'exemple du pitLéo avec quelques fonctions qui tourne sous angular ( Lire la doc )</p>
 </h3>
 <h4>Dernier Git le 27 janvier 2016</h4>
 <h5>Acksop</h5>
 <h6>POO.formation.dev</h6>
 </article>