<article>
 <h1>intégration du moteur d'écriture à la façon wikini</h1>
 <span class='date'><span class='jour'>2</span><br/><span class='mois'>JUIN</span><br/><span class='annee'>2016</span></span>
 <h2>Ce qui suit est le fichier formatté dans DATA et généré à la volé par le formatteur Wikini</h2>
 <?php echo $this->page['Wikinitext']->formated_text ?>
 <h3>Voici ce qu'il reste a faire</h3>
 <p class='del'>Intégrer les petits bogue de l'application de formattage et vérifier le tout fonctionnel</p>
 <p class='del'>Intégrer un appel d'action directement dans le core du wikini</p>
 <p class='del'>Intégrer un chargement handler spécifiques afin de pouvoir éditer le fichier text<p>
 <p class='del'>Intégrer des formatters spécifiques sous forme de fonctions pour ajouter un plus aux pages</p>
 <p class='del'>Simplifier l'appel de la variable créée dans la modele afin d'appeler le text formatté en HTML dans la vue ou le controlleur</p>
 <h4>Dernier Git le 3 juin 2016</h4>
 <h5>Acksop</h5>
 <h6>POO.formation.dev</h6>
 </article>