<article>
 <h1>intégration du moteur d'écriture à la façon markdown</h1>
 <span class='date'><span class='jour'>8</span><br/><span class='mois'>AOUT</span><br/><span class='annee'>2016</span></span>
<<h2>Ce qui suit est le fichier formatté dans DATA et généré à la volé par le formatteur parseDown:</h2>
 <?php echo $this->page['MarkDowntext']->formated_text ?>
 <h3>Voici ce qu'il reste a faire
 <p>Intégrer le tout dans une base de donnée avec une DAL BDD n'utilisant que PDO</p>
 <p>Intégrer un systeme de creation d'edition et de sauvegarde directement sur la page</p>
 <p>Intégrer un systeme d'edition mulitples en cas de fichier de mème nom et de formatter différents</p>
 <p>Intégrer un systeme d'edition des articles de facon indépendante dont chacun serait contenu dans un fichier créé dynamiquement</p>
 <p>Finaliser les possibilité de la lib Parse-down pour que l'example colle à celui situé à <a href="http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html">l'exemple trouvé sur internet</a>, en l'occurence les tableau, l'affichage sous format mathématqiue et les notes de bas de page ne fonctionnne pas</p>
 </h3>
 <h4>Dernier Git le 3 aout 2016</h4>
 <h5>Acksop</h5>
 <h6>POO.formation.dev</h6>
 </article>