<article>
<h1>intégration d'un affichage des paramètres pour mieux les manipuler</h1>
 <span class='date'><span class='jour'>3</span><br/><span class='mois'>JUIN</span><br/><span class='annee'>2016</span></span>
  <?php echo $ctr->modele->url; ?>
 <h3>voici comment tester :</h3>
 <p><a target='_self' href='http://poo.formation.dev/acceuil/acceuil?handler=edit'>http://poo.formation.dev/acceuil/acceuil?handler=edit</a></p>
 <p><a target='_self' href='http://poo.formation.dev/acceuil/varname/var'>http://poo.formation.dev/acceuil/varname/var</a></p>
 <p><a target='_self' href='http://poo.formation.dev/acceuil/categorie/type/date/horaire/nomArticle'>http://poo.formation.dev/acceuil/categorie/type/date/horaire/nomArticle</a></p>
 <p><a target='_self' href='http://poo.formation.dev/acceuil?action=var'>http://poo.formation.dev/acceuil?action=var</a></p>
 <p><a target='_self' href='http://poo.formation.dev/acceuil/wikini/example/markdown/example/WYMD/edit'>http://poo.formation.dev/acceuil/wikini/example/markdown/example/WYMD/edit</a></p>
 <h3>Voici ce qu'il reste a faire</h3>
 <p>Intégrer les petits bogues des différents types de paramètres et vérifier le tout fonctionnel ( par exemple la revue de paramètre de type standart page.php?action=var ne semble pas donner quoi que ce soit )</p>
 <h4>Dernier Git le 3 juin 2016</h4>
 <h5>Acksop</h5>
 <h6>Advanced.POO.formation.dev</h6>
 </article>