.done-true {
	text-decoration: line-through;
	color: grey;
}
body, table{
	max-width: 700px;
	margin: auto;
	padding: 10px;
}
ul.menu  {
  font-size: 17px;
  font-weight: 600;  
  padding-left: 0;
}

ul.menu > li {
	display: inline;
	padding-right: 20px;
}

ul.menu > li a {
	color: grey;
}

ul.menu > li a:hover{
	text-decoration: none;
	color: darkSlateGrey;
	border-top: 15px solid grey;
	border-bottom: 1px solid grey;
	padding-bottom: 12px;
	padding-top: 12px;
}
ul.menu > li a:active{
	text-decoration: capitalyse;
	color: darkSlateGrey;
	background-color: gray;
	border-top: 15px solid grey;
	border-bottom: 1px solid grey;
	padding-bottom: 1px;
	padding-top: 1px;
}
ul.menu > li a:focus{
	text-decoration: none;
	color: darkSlateGrey;
	border-top: 15px solid whiteSmoke;
	border-bottom: 1px solid whiteSmoke;
	padding-bottom: 12px;
	padding-top: 12px;
}

