<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/img/GED/Image1.png" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="/img/GED/Image2.png" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="/img/GED/Image3.png" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="col-md-12 top-menu-header">
  <div class="col-md-offset-3 col-md-9">
    <ul>
      <li><a href="/GED_no-admin"<?php echo isThePage($this->page['name'],'GED_no-admin') ;?>>FRONTEND - GED</a></li>
      <li><a href="/GED_acceuil"<?php echo isThePage($this->page['name'],'GED_acceuil') ;?>>HOME - GED</a></li>
      <li><a href="/GED_admin"<?php echo isThePage($this->page['name'],'GED_admin') ;?>>BACKEND- GED</a></li>
    </ul>
  </div>
</div>