<link rel="stylesheet" type="text/css" href="css/btn-TypeGoogle.css">
<link rel="stylesheet" type="text/css" href="lib/angularGED/css/GED-style.css">
<link rel="stylesheet" type="text/css" href="lib/angularGED/bootstrap-3.3.7-dist/css/bootstrap.min.css">

<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="lib/angularGED/jQuery-File-Upload-9.18.0/css/style.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="lib/angularGED/jQuery-File-Upload-9.18.0/css/jquery.fileupload.css">

<style>

ul {
    list-style : none;
    margin : 0px;
    padding : 0px;
    padding-left : 25px;
}

li {
    padding-left : 20px;
    line-height : 18px;
    cursor : pointer;
}

li.folder {
    background : url("img/GED/folder.png") no-repeat left center;
}

li.file {
    background : url("img/GED/file.png") no-repeat left center;
}
</style>